### ISSUE TITLE
npm run dev generate warnings

### ISSUE THREAD

**Issue by Akiyamka** [Metnew/vue-element-starter#5]
look like in dev dependences missing some css preprocessor
```
> Vue-Element-Starter@1.0.0 dev C:\OpenServer\domains\tdhelp
> node build/server.js

webpack: wait until bundle finished:


 WARNING  Compiled with 1 warnings                                                                                                                     14:07:57

 warning  in ./theme/index.css

(Emitted value instead of an instance of Error)   resolve-url-loader cannot operate: CSS error
  C:\OpenServer\domains\tdhelp\theme\index.css:4974:5: missing '}'
  at error (C:\OpenServer\domains\tdhelp\node_modules\css\lib\parse\index.js:62:15)

 @ ./theme/index.css 4:14-118 13:2-17:4 14:20-124
 @ ./client/app.js
 @ ./client/index.js
 @ multi webpack-hot-middleware/client?reload=true ./client/index.js

> App is running at http://localhost:4000

Hash: 3a8998df68430a53996e
Version: webpack 2.4.1
Time: 6982ms
                                Asset       Size  Chunks                    Chunk Names
 b02bdc1b846fd65473922f5f62832108.ttf    13.2 kB          [emitted]
d2f69a92faa6fe990d2e613c358be705.woff       8 kB          [emitted]
                            client.js    5.37 MB       0  [emitted]  [big]  client
                           index.html  405 bytes          [emitted]
                          favicon.ico    27.8 kB          [emitted]
chunk    {0} client.js (client) 1.94 MB [entry] [rendered]
   [48] ./client/index.js 241 bytes {0} [built]
   [49] (webpack)-hot-middleware/client.js?reload=true 6.68 kB {0} [built]
   [50] ./~/ansi-html/index.js 4.26 kB {0} [built]
   [51] ./~/ansi-regex/index.js 135 bytes {0} [built]
   [74] ./client/app.js 1.68 kB {0} [built]
  [144] ./~/querystring-es3/index.js 127 bytes {0} [built]
  [145] ./~/strip-ansi/index.js 161 bytes {0} [built]
  [147] ./~/normalize.css/normalize.css 952 bytes {0} [built]
  [148] ./client/styles/index.scss 1.19 kB {0} [built]
  [149] ./theme/index.css 1.03 kB {0} [built]
  [150] ./client/components/App/index.vue 1.8 kB {0} [built]
  [171] (webpack)-hot-middleware/client-overlay.js 1.82 kB {0} [built]
  [172] (webpack)-hot-middleware/process-update.js 3.88 kB {0} [built]
  [174] (webpack)/buildin/module.js 517 bytes {0} [built]
  [176] multi webpack-hot-middleware/client?reload=true ./client/index.js 40 bytes {0} [built]
     + 162 hidden modules

WARNING in ./~/css-loader!./~/resolve-url-loader!./theme/index.css
(Emitted value instead of an instance of Error)   resolve-url-loader cannot operate: CSS error
  C:\OpenServer\domains\tdhelp\theme\index.css:4974:5: missing '}'
  at error (C:\OpenServer\domains\tdhelp\node_modules\css\lib\parse\index.js:62:15)
 @ ./theme/index.css 4:14-118 13:2-17:4 14:20-124
 @ ./client/app.js
 @ ./client/index.js
 @ multi webpack-hot-middleware/client?reload=true ./client/index.js
Child html-webpack-plugin for "index.html":
         Asset     Size  Chunks  Chunk Names
    index.html  1.48 MB       0
    chunk    {0} index.html 541 kB [entry] [rendered]
        [0] ./~/lodash/lodash.js 540 kB {0} [built]
        [1] ./~/html-webpack-plugin/lib/loader.js!./build/index.html 779 bytes {0} [built]
        [2] (webpack)/buildin/global.js 509 bytes {0} [built]
        [3] (webpack)/buildin/module.js 517 bytes {0} [built]
webpack: Compiled with warnings.
```

**Comment by Metnew** [comment]
Hi, it's not an issue of dependencies, it's problem with `theme/index.css`:
<img width="446" alt="2017-05-02 18 51 33" src="https://cloud.githubusercontent.com/assets/10862289/25626557/92cbf7ce-2f68-11e7-858a-b6f79cb8966f.png">
Element generated invalid CSS. I guess monkey-patching of `index.css` is the best solution
